name: First WorkFlow 
on: workflow_dispatch #trigger
jobs: 
  first-job:
    runs-on: ubuntu-latest #vm
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done -bye!"
      - name: Print multiple messages
        run: |
            echo "output1"
            echo "output2"
            echo "output3"
